version: '3.9'

services:
  tvheadend:
    container_name: tvheadend
    image: lscr.io/linuxserver/tvheadend:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuching
      - RUN_OPTS= #optional
    volumes:
      - /data/tvheadend/data:/config
      - /data/tvheadend/recordings:/recordings
    ports:
      - 9981:9981
      - 9982:9982
    devices:
      - /dev/dri:/dev/dri #optional
      - /dev/dvb:/dev/dvb #optional
    restart: unless-stopped